name: CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      version: ${{ steps.getVersion.outputs.version }}
      artifactName:
    steps:
    - name: 获取信息
      id: getInfo
      run: |
        echo "repositoryName=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
        echo "actionUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
    - name: 获取版本
      if: github.event_name == 'push' && startsWith('github.ref', 'refs/tags/')
      id: getVersion
      run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - name: 设置 artifact 的名称
      id: getArtifactName
      uses: actions/github-script@v8
      with:
        script: |
          const onEventName = "${{ github.event_name }}";
          const refName = "${{ github.ref }}";
          let artifactName = "${{ steps.getInfo.outputs.repositoryName }}-CI-Dispatch-Build-${{ github.run_number }}";
          if (onEventName == "pull_request") {
            artifactName = "${{ steps.getInfo.outputs.repositoryName }}-CI-PR_${{ github.event.pull_request.number }}-Build-${{ github.run_number }}";
          }
          if(onEventName == "push" && refName.startwith("refs/tags/")){
            artifactName = "${{ steps.getInfo.outputs.repositoryName }}-Release-${{ steps.getVersion.outputs.version }}";
          }
          core.info(`Artifact name: ${artifactName}`);
          core.setOutput('name', `${artifactName}`);
    - name: 拉取代码
      uses: actions/checkout@v6
    - name: 安装java8
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 设置 pom.xml 的版本号
      if: github.event_name == 'push' && startsWith('github.ref', 'refs/tags/')
      run: |
        echo "::warning::对 pom.xml 中 project 版本号进行设置，设置的版本号为 ${{ steps.getVersion.outputs.version }}"
        mvn versions:set -DnewVersion=${{ steps.getVersion.outputs.version }}
    - name: 获取 pom.xml 的信息
      id: getPomInfo
      run: |
        echo "groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: Show get pom.xml gav info
      run: |
        echo Group id: ${{ steps.getPomInfo.outputs.group-id }}
        echo Artifact id: ${{ steps.getPomInfo.outputs.artifact-id }}
        echo Version: ${{ steps.getPomInfo.outputs.version }}
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
    - name: 获取脚本资源
      uses: actions/checkout@v5
      with:
        repository: 'stevei5mc/McStartServer'
        path: ./script
    - name: 整理脚本资源
      run: |
        pwd
        cp ./script/server_script/Windows/*.bat staging
        cp ./script/server_script/Linux/*.sh staging
        cd ./staging
        zip -r Windows-script.zip ./*.bat
        zip -r Linux-script.zip ./*.sh
        ls -lah
        cd ../
    - name: 收集构建文件
      uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.getArtifactName.outputs.name }}
        path: staging

  release:
    runs-on: ubuntu-slim
    if: github.event_name == 'push' && startsWith('github.ref', 'refs/tags/')
    needs: build
    timeout-minutes: 5
    steps:
    - name: 拉取代码
      uses: actions/checkout@v6
    - name: 下载发布需要的文件
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifactName }}
        path: staging
    - name: 发布新版本
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ needs.build.outputs.version }}
        name: ${{ needs.build.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: ./docs/changelogs/${{ needs.build.outputs.version }}.md
        artifacts: ./staging/*.*